Repository radical-cybertools/ROSE, pull requests merged in 2025-02, with the labels that each got.

#16 Feature/al algo selector
  examples/algo_selector/active_1.py
  examples/algo_selector/active_2.py
  examples/algo_selector/check_mse.py
  examples/algo_selector/run_me.py
  examples/algo_selector/sim.py
  examples/algo_selector/train.py
  rose/learner.py
Labels: new feature

#23 Feature/docs
  .github/workflows/ci.yml
  .gitignore
  docs/assets/icon.svg
  docs/assets/rose-removebg-preview.png
  docs/getting-started/dry-run.md
  docs/getting-started/faq.md
  docs/getting-started/installation.md
  docs/index.md
  docs/styles/custom.css
  docs/user-guide/acl-metrics.md
  docs/user-guide/advanced-acl-workflow.md
  docs/user-guide/basic-acl-workflow.md
  docs/user-guide/target-resources.md
  docs/user-guide/visualization.md
  mkdocs.yml
Labels: documentation

#26 refine docs
  docs/getting-started/faq.md
  docs/index.md
Labels: documentation

#27 Algorithm Selector tutorial
  examples/algorithm_selector/algorithm-selector-tutorial.ipynb
Labels: enhancement
